worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location = / {
            rewrite ^ /static/index.html last;
        }

        location / {
            try_files $uri =404;
        }

        location /ttv {
            return 301 https://www.twitch.tv/blackhat_magic;
        }

        location /twitch {
            return 301 https://www.twitch.tv/blackhat_magic;
        }

        location /yt {
            return 301 https://www.youtube.com/c/BlackHatMagic;
        }

        location /youtube {
            return 301 https://www.youtube.com/c/BlackHatMagic;
        }

        location /t {
            return 301 https://www.twitter.com/Black_HatMagic;
        }

        location /twt {
            return 301 https://www.twitter.com/Black_HatMagic;
        }

        location /twitter {
            return 301 https://www.twitter.com/Black_HatMagic;
        }

        location /gitlab {
            default_type text/plain;
            return 200 "Well aren't you a nosy one? Gitlab coming soon (tm).";
        }

        location /git {
            return 301 https://www.github.com/BlackHat-Magic;
        }

        location /github {
            return 301 https://www.github.com/BlackHat-Magic;
        }

        location /reddit {
            return 301 https://www.reddit.com/u/BlackHatMagic1545;
        }

        location /email {
            return 301 mailto:BlackHatMagic@gmail.com;
        }

        location /mail {
            return 301 mailto:BlackHatMagic@gmail.com;
        }

        location /discord {
            return 301 https://discord.gg/dqSusZqenq;
        }

        location /discord-profile {
            return 301 https://discord.com/users/272197511769227264;
        }

        location /steam {
            return 301 https://steamcommunity.com/id/Black_Hat_Magic/;
        }

        location /gfapp {
            return 301 https://youtu.be/dQw4w9WgXcQ;
        }

        location /gfapplication {
            return 301 https://youtu.be/dQw4w9WgXcQ;
        }

        location /of {
            return 301 https://youtu.be/fC7oUOUEEi4;
        }

        location /onlyfans {
            return 301 https://youtu.be/fC7oUOUEEi4;
        }

        location /lstoastgf {
            return 301 https://docs.google.com/forms/d/e/1FAIpQLSdsLM7-g0ACPAKb7HGVc6y1k5QS2c6hhpxxnVzKyQbfslRHw/viewform;
        }

        location /static/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}
